baseURL = 'https://thyke.github.io/'
theme = 'PaperMod'
defaultContentLanguage = "tr" # Varsayılan dil
languageCode = 'en-us'
title = 'Faruk Yıldırım | C++ Developer'

[params]
    defaultTheme = "dark"
    description = "Senior C++ / Unreal Engine Developer"

    # --- ORTA KISIM (Profile Mode) AYARLARI ---
    [params.profileMode]
        enabled = true # Profile Mode aktif kalacak
        title = "Faruk Yıldırım"
        subtitle = "Senior C++ / Unreal Engine Developer"
        imageUrl = "https://github.com/thyke.png"
        imageTitle = "Faruk Yıldırım"
        
        # ORTADA GÖRÜNECEK BUTONLAR (Ana Sayfaya özel)
        [[params.profileMode.buttons]]
            name = "Projects"
            url = "/projects"
        [[params.profileMode.buttons]]
            name = "Blog"
            url = "/blog"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Thyke"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/faruk-y%C4%B1ld%C4%B1r%C4%B1m-aa1433103/"

# --- ÇOK DİLLİ KONFİGÜRASYON (Sağ Üst Menü ve Dil Ayarı) ---

[languages]
  [languages.tr]
    languageName = "Türkçe"
    contentDir = "content/tr"
    weight = 1
    title = "Faruk Yıldırım - C++ Geliştirici"
    languageCode = "tr"
    
    [languages.tr.menu]
        # SAĞ ÜST MENÜ (TÜRKÇE)
        [[languages.tr.menu.main]]
            identifier = "projeler"
            name = "Projeler"
            url = "/projects/"
            weight = 10
            
        [[languages.tr.menu.main]]
            identifier = "blog"
            name = "Blog & Teknik Notlar"
            url = "/blog/"
            weight = 20
            
        [[languages.tr.menu.main]]
            identifier = "hakkimda"
            name = "Hakkımda"
            url = "/about/" # Yeni statik sayfa eklenmiş oldu
            weight = 30
            
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    title = "Faruk Yıldırım - C++ Developer"
    languageCode = "en"
    
    [languages.en.menu]
        # SAĞ ÜST MENÜ (İNGİLİZCE)
        [[languages.en.menu.main]]
            identifier = "projects"
            name = "Projects"
            url = "/projects/"
            weight = 10
            
        [[languages.en.menu.main]]
            identifier = "blog"
            name = "Blog & Technical Notes"
            url = "/blog/"
            weight = 20
            
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About Me"
            url = "/about/"
            weight = 30